### ISSUE TITLE
需要增加依赖

### ISSUE THREAD

**Issue by sbwtw** [PointTeam/PointDownload#10]
下载完成时播放声音使用的是
QSound::play(":/tone/resources/Tone/complete.wav");
QSound需要依赖pulseaudio，否则运行时不会播放声音并且有这样的错误：
PulseAudioService: pa_context_connect() failed

或者改为使用QMediaPlayer

**Comment by PointTeam** [comment]
非常抱歉，这几天比较忙，所以这么晚才回复。这个当时是在Deepin上还有openSUSE上开发的，默认就没有报这个问题，应该是不同发行版本支持的不太一样吧。QMediaPlayer兼容的比较好吗？

**Comment by sbwtw** [comment]
我的环境是archlinux, 那个依赖在源里就有而且很小, 我觉得加个依赖就行没必要改代码了

**Comment by PointTeam** [comment]
嗯，把那个依赖的写上就好了
