### ISSUE TITLE
建议修改程序内部硬编码的执行文件路径

### ISSUE THREAD

**Issue by sbwtw** [PointTeam/PointDownload#11]
在datacontroler.h和unifiedinterface.h中定义了pointdownload和pointpopup执行文件的路径，对于debian系的，程序一般安装在/opt下面，但是对于archlinx，/opt早已经不放任何东西了，调用pointdownload和pointpopup是否能改成QProcess->start("pointpopup", ....); 这样只需要各个平台下配置好环境变量就能统一调用了，强制在所有平台上安装在同样的目录有些不合理。

**Comment by Match-Yang** [comment]
好，后面按照你说的方式改
