### ISSUE TITLE
xware组件不可用

### ISSUE THREAD

**Issue by 1dot75cm** [PointTeam/PointDownload#12]
测试平台：centos 7 x86_64
版本：https://github.com/PointTeam/PointDownload/commit/ddf5919440907a3f407f93cc29c41df007d83c9f
问题：
- xware 可以正常登陆，添加普通下载任务(如[qq](http://dldir1.qq.com/qqfile/qq/QQ6.7/13458/QQ6.7.exe)) ，point界面速度一直为0，登陆 yuancheng.xunlei.com 发现提示网络不可达。但在网页添加下载任务就可以正常下载。
- 添加 bt 下载任务，程序返回以下错误：

```
[xware info] Binding successful! => Login successful 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
已放弃(吐核)
```

**Comment by choldrim** [comment]
好，立即处理！

**Comment by choldrim** [comment]
@1dot75cm 测试结果如何？

**Comment by 1dot75cm** [comment]
测试平台：centos 7 x86_64
版本：https://github.com/PointTeam/PointDownload/commit/bfb99a7c5f1449c8d225e60225dc030eb25ff0c3
问题：
现在向xware添加bt, magnet, 普通任务，有时返回错误101，重新添加任务就好了。
下载magnet任务，不能选择下载某个文件，只能全部下载。
其他问题目前还没发现。

**Comment by PointTeam** [comment]
101错误的问题我们尽快看看；
现在下载列表是只能全选的，这个功能会在重构后做好。我们准备近期开始对整个框架进行重构改进:-D

**Comment by choldrim** [comment]
101 的错误是迅雷反馈的，它的源码中查到对应的错误是 LIST_TASK_ERR_MACHINE_NOT_FOUND 
估计是在登录后的绑定过程中，迅雷服务器还没接收到绑定的机器信息
或者，可否说一下这一问题的重现步骤呢？谢谢

**Comment by 1dot75cm** [comment]
@choldrim  这个错误在第一次添加下载任务的时候会出现，查看yuancheng.xunlei.com报101，之后删除任务，再次添加就正常了。不知是否是网络不好，服务器还没收到已绑定机器的状态信息，就提交下载任务了。
