### ISSUE TITLE
有2个地方显示不完全

### ISSUE THREAD

**Issue by sbwtw** [PointTeam/PointDownload#13]
当下载列表过长时，最下面一个任务展开时，有一部分挡住了

提示窗口文字为多行时，最下面有部分挡住，虽然滚动条可以使用但是由于这个窗口出现时间很短，滚动条基本没什么作用

**Comment by choldrim** [comment]
收到 @Match-Yang

**Comment by Match-Yang** [comment]
这个设计有欠缺，再想想提示窗口以怎样的方式提示人性化一点
