### ISSUE TITLE
ubuntu 14.10 PointDownload 托盘位置不正常

### ISSUE THREAD

**Issue by ustcltx** [PointTeam/PointDownload#15]
![2015-01-08 18 35 25](https://cloud.githubusercontent.com/assets/6998333/5662068/adafb024-976e-11e4-8bdc-44e2cbf95d19.png)

托盘霸占unity桌面左上角，点击左上角触发主窗口显示的事件。shell下启动没有什么报错。。。

**Comment by sbwtw** [comment]
貌似是unity的原因，研究一下
qt-project.org/doc/qt-4.8/qsystemtrayicon.html#note-content-197

**Comment by PointTeam** [comment]
确实是unity的原因，不过我们是支持unity原生托盘的，只是在deepin论坛提供的软件包是不支持的，请自行编译打包安装（会根据你的桌面环境确定要不要加入unity托盘的支持），说明：https://github.com/PointTeam/PointDownload/wiki/Ubuntu(Kylin)%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E

**Comment by ustcltx** [comment]
其实是unity桌面的bug，打上一个ppa补丁后所有托盘都正常了。http://m.webupd8.org/2013/05/how-to-get-systray-whitelist-back-in.html?m=1

**Comment by PointTeam** [comment]
好的，谢谢，我们会去看的
