### ISSUE TITLE
圆形托盘下载速度显示异常。

### ISSUE THREAD

**Issue by ustcltx** [PointTeam/PointDownload#16]
![2015-01-10 22 22 56](https://cloud.githubusercontent.com/assets/6998333/5691883/72629d42-9917-11e4-97e8-e084103bb933.png)

无论速度是多少都显示 0.1KB/S

**Comment by PointTeam** [comment]
谢谢你的反馈，这个问题我们已经知道，不过会等到下次重构后才修复这个问题:-D
