### ISSUE TITLE
ubuntu 编译1.2.0版报错。

### ISSUE THREAD

**Issue by jlzsss** [PointTeam/PointDownload#20]
报错信息如下：
mv: 无法获取"debian/pointdownload/opt/PointDownload/bin/PointDownload" 的文件状态(stat): 没有那个文件或目录
make[1]: **\* [override_dh_auto_install] 错误 1
make[1]:正在离开目录 `/home/jlz/PointDownload'
make: **\* [binary] 错误 2
dpkg-buildpackage: 错误: fakeroot debian/rules binary 提供错误退出状态 2
作者能否修复一下。

**Comment by choldrim** [comment]
不好意思，回复晚了，已修复。

**Comment by jlzsss** [comment]
不好意思 又来打搅您了。
我已经编译好了，安装上以后也可以运行，可是xware一直登录不上，自动登录手动登录都试过了，可是还是不行，不知道是不是bug。

**Comment by choldrim** [comment]
登不上有提示什么吗？

需要出现，“登录服务已启用”，才能登录迅雷
不要勾“自动登录”，自动登录有时验证码获取不到
![image](https://cloud.githubusercontent.com/assets/6734555/7515265/29c57860-f4f8-11e4-956b-5d51458124df.png)

**Comment by jlzsss** [comment]
没有提示，我这里点击登录，显示正在登录，后来又回到登录界面。不知道为什么我这没有提示信息。

**Comment by choldrim** [comment]
#21
