### ISSUE TITLE
下载地址失效了

### ISSUE THREAD

**Issue by appdev** [PointTeam/PointDownload#22]
由于深度社区改版，原来的帖子失效了

**Comment by choldrim** [comment]
你说的是哪一个页面？我试了可以下载　:0
直接这里下载
http://bbs.deepin.org/forum.php?mod=viewthread&tid=21124
或者是从github上clone一份，按wiki的打包方式自己打个包就行了，打包过程比较简单

**Comment by appdev** [comment]
谢谢。我说的地址是你rreadme 哪里写的地址。

**Comment by choldrim** [comment]
已修，谢谢提醒  :+1:
