### ISSUE TITLE
在elementaryos上启动闪退，命令下执行/opt/Point/PointDownload/PointDownload报错

### ISSUE THREAD

**Issue by amendgit** [PointTeam/PointDownload#25]
./PointDownload: symbol lookup error: ./PointDownload: undefined symbol: _ZN7QString13toUtf8_helperERKS_

是不是缺少什么依赖包，要安装qt的什么组件吗？

**Comment by sbwtw** [comment]
ldd ./PointDownload 可以看看有没有缺少的 .so 依赖
如果是编译安装的话应该不会出这个错

**Comment by amendgit** [comment]
那能不能给一下编译安装的大致说明，貌似没有找到，非常感谢。

**Comment by choldrim** [comment]
wiki 里面有：https://github.com/PointTeam/PointDownload/wiki
（迅雷下载暂时用不了）

**Comment by amendgit** [comment]
找到编译说明了: https://github.com/PointTeam/PointDownload/wiki/Ubuntu(Kylin)%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E
非常感谢你们的辛苦开发. 再问个问题,编译出来的不支持迅雷的话, 那有什么方法安装支持中文吗? 或者未来的版本会在ElementaryOS等其他发行版上提供能支持迅雷下载的安装方式呢?

**Comment by choldrim** [comment]
> 安装支持中文

具体一点是指？

> 或者未来的版本会在ElementaryOS等其他发行版上提供能支持迅雷下载的安装方式呢?

因为Linux发行版过多，暂时不会考虑其他发行版的编译打包，缺少的发行版安装说明暂时依赖其他发行版打包者帮我们完成
迅雷模块，因为迅雷服务器对xware的固件支持时好时不好，所以并没有放多大精力去修复

还有，感谢你的支持！  :)

**Comment by amendgit** [comment]
在ElementaryOS上编译安装完成 & 关闭此issue & 感谢软件的作者
