### ISSUE TITLE
Ubuntu14.04LTS 下载闪退

### ISSUE THREAD

**Issue by lxgsbqylbk** [PointTeam/PointDownload#7]
输入下载Address后 点左边的button闪退

**Comment by PointTeam** [comment]
左边的button指的是什么呢？

**Comment by lxgsbqylbk** [comment]
这这样的
我的环境时Ubuntu14.04LTS
Qmake version 3.0
qt version 5.2.1

程序编译运行后 cpu usage netspeed这些都是正常的
在上方输入Download URL后
比如我输入的
http://acm.hdu.edu.cn/data/images/C140-1007-1.rar
不知道怎么开始下载？
点放大镜图标没反应
点放大镜左边那个有３条横线那个图标界面直接退出了 但进程还在 要去终端kill一次
点ＵＲＬ右边那个公文包图标 打开了PointDownload下载目录 这个应该时对的
代码我还没看过 只是测了下功能
初学C++想用这个学习学习 呵呵

2014-10-11 21:00 GMT+08:00 point-team notifications@github.com:

**Comment by PointTeam** [comment]
你编译的是master分支吧？那个分支比较久，最新的版本都在develop分支，你先使用develop分支进行编译吧，然后参考： https://github.com/PointTeam/PointDownload/tree/develop/debian 详细看清楚这里面做了哪些设置，这会对你正确运行程序很有必要，有问题可以尽管跟我们提问
